#!/bin/bash


#debo de leer lo que hay en el documento 

#perimo debemos de verificar que exista el archivo
if [ -e $1 ]; then
	
	#el archivo entonces si existe 

	while IFS= read -r name 
	do
		#en este momento "name" es el que tiene el nombre del usuario 

		user_name=`w | grep "$name"`

		#parametro -z indica si la cadena esta vacia 

		if [ -z "$user_name" ]; then
			echo "el usuario $name no se encuentra conectado"

		else
			echo "el usuario $name esta conectado"
		
		fi
			
	done < $1	

else
	echo "el archivo no existe"
fi



